@echo off
setlocal EnableExtensions EnableDelayedExpansion

REM ================================
REM Create .env safely (ASCII only)
REM ================================

if exist .env (
    echo .env already exists, skipping creation.
    goto START
)

echo Creating .env file...

> .env (
    echo # Inventix AI - Environment Configuration
    echo # Auto-generated by deploy.bat
    echo.
    echo GEMINI_API_KEY=
    echo GEMINI_MODEL=gemini-1.5-flash
    echo.
    echo BACKEND_HOST=0.0.0.0
    echo BACKEND_PORT=8000
    echo DEBUG=false
    echo.
    echo SECRET_KEY=change-this-to-a-secure-random-string
    echo JWT_ALGORITHM=HS256
    echo JWT_EXPIRATION_MINUTES=120
    echo.
    echo GOOGLE_CLIENT_ID=
    echo GOOGLE_CLIENT_SECRET=
    echo GOOGLE_REDIRECT_URI=http://localhost:3000/auth/callback
    echo.
    echo NEXT_PUBLIC_API_URL=http://localhost:8000
    echo NEXT_PUBLIC_APP_NAME=Inventix AI
)

echo .env created successfully.

:START
echo Starting services...
docker compose up --build

pause
